flowThroughs ={
'C:\Data\FlowThroughSug.xlsx', ...
'C:\Data\FlowThroughProt.xlsx', ...
'C:\Data\FlowThrough_BnImR_2pA_TGAmCC.xlsx', ...
'C:\Data\FlowThrough_ImR_2pA_TGAmCC', ...
'C:\Data\FlowThrough_ImR_4pA_TGAmCC'};

doAnalysis=false;
for I=1:length(flowThroughs)
    batchExcel=flowThroughs{I};
    Master
end

